### PR TITLE
Update to v1.64.0

### PR DESCRIPTION
**Pull request by marcoesters**
Update rust to the latest version. `cargo-license-bundle` needs an updated `rust` version to compile, so the we update to the latest version.

# Package info

Home: https://www.rust-lang.org
Development: https://github.com/rust-lang/rust
Documentation: https://doc.rust-lang.org/std/
Diff: https://github.com/rust-lang/rust/compare/1.56.0...1.64.0

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
The following items could be modified in order to cover the requested changes made by the linter:

license_file: COPYRIGHT

doc_source_url: https://github.com/rust-lang/rust/tree/master/src/doc

license_url: https://github.com/rust-lang/rust/blob/master/COPYRIGHT

**Comment by marcoesters** [comment]
> The following items could be modified in order to cover the requested changes made by the linter:
> 
> license_file: COPYRIGHT
> 
> doc_source_url: https://github.com/rust-lang/rust/tree/master/src/doc
> 
> license_url: https://github.com/rust-lang/rust/blob/master/COPYRIGHT

Adding a license_file breaks for Windows because conda-build looks for them in the root directory of the source. However, they are in subdirectories.

**Review by ryanskeith — APPROVED** [review]
Looks good to me.

**Review by AndrewVallette — APPROVED** [review]
LGTM! I'd say build the `win-64` package on a dev instance if Prefect continues to be problematic.

**Review by varlackc — APPROVED** [review]
LGTM

**Review by katietz — APPROVED** [review]
looks good. the thing I looked into more detail in is that .bat/.sh thing on windows ... AFAICS your simpkification here is fine
Side-note: I like those condition tenaries in bash, but maybe it would be more clear to use paranthesis for the left part?

**Comment by marcoesters** [comment]
> looks good. the thing I looked into more detail in is that .bat/.sh thing on windows ... AFAICS your simpkification here is fine Side-note: I like those condition tenaries in bash, but maybe it would be more clear to use paranthesis for the left part?

I also really like ternary operators.

You mean `[[ $(uname) == Darwin ]]` or which parentheses?

**Comment by marcoesters** [comment]
Built it on Concourse instead since Prefect is not working.

**Pull request merged**
